language: go

services:
  - mysql
  - redis

go:
  - 1.2
  - 1.3
  - release
  - tip

install:
  - go get code.google.com/p/go.tools/cmd/vet
  - go get github.com/tools/godep
  - $HOME/gopath/bin/godep restore ./...

script: go vet ./... && go test ./... -v

before-script:
  - mysql -u root < ./resources/mysql/paymentd.test.sql
  - export PAYMENTD_MYSQLTEST=true
  - export PAYMENTD_MYSQLTEST_PAYMENTDSN="root@tcp(localhost:3306)/fritzpay_payment_test?charset=utf8mb4&parseTime=true&loc=UTC&timeout=1m&wait_timeout=30&interactive_timeout=30"
  - export PAYMENTD_MYSQLTEST_PRINCIPALDSN="root@tcp(localhost:3306)/fritzpay_principal_test?charset=utf8mb4&parseTime=true&loc=UTC&timeout=1m&wait_timeout=30&interactive_timeout=30"
