language: go

go:
  - 1.3
  - tip

install:
  - go get code.google.com/p/go.tools/cmd/vet
  - go get github.com/tools/godep
  - $HOME/gopath/bin/godep restore ./...

script: go vet ./... && go test ./... -v
